### PR TITLE
Add references for users in Group model

### PR DESCRIPTION
**Pull request by JuanequeX**
# Description
 - We Added a `user_id` field in groups table  to solve the reference in groups to users, we modify both models to have this connection.

# Testting
you can see the test in models folder, we testing to secure the association are success ed

### CODE REVIEW

**Review by YilKanda — DISMISSED** [review]
LGTM!

**Review by CUBOFIG — APPROVED** [review]
LGTM! 🧑🏻‍🚀 ☄️

**Review by CUBOFIG — DISMISSED** [review]
LGTM! ✨

**Review by CUBOFIG — APPROVED** [review]
LGTM! ⚡️

**Review by jestradadeveloper — APPROVED** [review]
LGTM

**Pull request merged**
