### PR TITLE
Change price in premium plan

### PR DESCRIPTION
**Pull request by JuanequeX**
# Description
 - Change at $99.00 to $3.00 cost of premium plan.
 
  ## Screenshots
image

### CODE REVIEW

**Review by EdsonMorfin — APPROVED** [review]
lgtm

**Review by jestradadeveloper — APPROVED** [review]
LGTM

**Review by jestradadeveloper — APPROVED** [review]
LGTM

**Review by CUBOFIG — APPROVED** [review]
LGMT

**Review by CUBOFIG — APPROVED** [review]
LGMT

**Review by adrianMRJ — APPROVED** [review]
LGTM

**Pull request merged**
